baseURL = "http://seiji.github.io/"
languageCode = "en-us"
title = "posts"
theme = "onetwothree"

pygmentsCodeFences = true
#pygmentsStyle = "manni"
pygmentsStyle = "pygments"

[params]
  twitter = ""
  navigation = ["about.md"]
  style = ""
