baseURL = "http://seiji.github.io/"
languageCode = "en-us"
title = "posts"
theme = "onetwothree"

pygmentsCodeFences = true
pygmentsStyle = "manni"

[params]
  twitter = ""
  navigation = ["about.md"]
  style = ""
