name: Build and Deploy
on:
  push:
    branches:
      - src
jobs:
  build:
    name: build-and-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        decks:
          # - aws-security-credential
          - aws-ssm-session-manager
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: peaceiris/actions-hugo@v2.2.3
        with:
          hugo-version: '0.58.3'

      - name: Build
        run: hugo --minify

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build mdx-deck
        run: |
          rm -Rf ./public/decks/${{matrix.decks}} && mkdir -p ./public/decks/${{matrix.decks}} && cd ./decks/${{matrix.decks}} && npm install && npm run build && ls -la && mv -i ./public/* ../../public/decks/${{matrix.decks}}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
