name: Build and Deploy
on:
  push:
    branches:
      - src
jobs:
  build:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # - uses: ./.github/actions/publish-gh-pages
      #   env:
      #     PUSH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
